[tool.poetry]
name = "advent_of_code"
version = "2019"
description = ""
authors = ["Alexey Dubrov <vhsw@ya.ru>"]

[tool.poetry.dependencies]
python = "^3.6.5"
networkx = "^2.4"
matplotlib = "^3.1.2"

[tool.poetry.dev-dependencies]
mypy = "^0.750"
pylint = "^2.4.4"
pytest = "^5.3.1"
black = "^19.10b0"
hypothesis = "^4.53.2"
flake8 = "^3.7.9"
termtosvg = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
