[tool.poetry]
name = "advent_of_code"
version = "2020"
description = ""
authors = ["Alexey Dubrov <vhsw@ya.ru>"]

[tool.poetry.dependencies]
python = "^3.9.1"
networkx = "^2.5"
matplotlib = "^3.3.3"
numpy = "^1.19.4"
click = "^7.1.2"
requests = "^2.25.0"
python-dotenv = "^0.15.0"
beautifulsoup4 = { extras = ["lxml"], version = "^4.9.3" }

[tool.poetry.dev-dependencies]
mypy = "^0.790"
pylint = "^2.6.0"
pytest = "^6.1.2"
black = "^20.8b1"
hypothesis = "^5.41.4"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pylint]
[tool.pylint.basic]
good-names = ["df", "fp", "ex"]
